"""Summarise TurboTax 2024 help XML (Forms/1040_24/dhtmlhelp), the UI image folder and
dialog pages, and resolve the interview's in-text help links against the help store.

Read-only on the install.  Usage:
    python -I summarize_assets.py [install-root] [out-dir]
Writes assets-summary.md and help-topics.csv (key, H1 title, text length) to out-dir.
Requires screens.jsonl from extract_screens.py in out-dir for the link-resolution section.
"""
import collections
import csv
import html
import json
import os
import re
import sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else r"C:\Program Files\TurboTax\Individual 2024"
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(os.path.abspath(__file__))
HELP = os.path.join(ROOT, r"Forms\1040_24\dhtmlhelp")
IMG = os.path.join(ROOT, r"64bit\local\img")
DLG = os.path.join(ROOT, r"64bit\local\dlg")

ENTRY = re.compile(r"<([A-Za-z0-9_]+)><!\[CDATA\[(.*?)\]\]></\1>", re.S)


def plain(h):
    h = re.sub(r"<script.*?</script>", " ", h, flags=re.S | re.I)
    h = re.sub(r"<[^>]+>", " ", h)
    return re.sub(r"\s+", " ", html.unescape(h)).strip()


L = ["# TurboTax 2024 desktop - help content, images and dialogs (static summary)\n",
     "Generated by `summarize_assets.py` (read-only scan).\n"]
help_rows = []
help_keys = {}
L.append("## Help XML files (`Forms/1040_24/dhtmlhelp`)\n")
L.append("| file | entries | key prefix | median text chars | what it is |\n|---|---|---|---|---|")
what = {
    "hyper.xml": "In-interview hyperlink help: the 'Learn More' / underlined-term popups (key = `hyp` + link target).",
    "taxhelp.xml": "Forms-mode help: one article per worksheet/form explaining how the form works in TurboTax.",
    "xrefer.xml": "Forms-mode cross-references: 'where does this line come from' jump lists (`top.gotoline`).",
    "govinst.xml": "Government instructions stub (one entry - the IRS instructions are not shipped here).",
}
for fn in ["hyper.xml", "taxhelp.xml", "xrefer.xml", "govinst.xml"]:
    s = open(os.path.join(HELP, fn), encoding="utf-8", errors="replace").read()
    ents = ENTRY.findall(s)
    lens = sorted(len(plain(v)) for _, v in ents) or [0]
    prefixes = collections.Counter(k[:3] for k, _ in ents)
    L.append("| %s | %d | %s | %d | %s |" % (fn, len(ents), ", ".join(prefixes), lens[len(lens) // 2], what[fn]))
    for k, v in ents:
        m = re.search(r"<H1>(.*?)</H1>", v, re.S | re.I)
        title = plain(m.group(1)) if m else ""
        help_rows.append((fn, k, title, len(plain(v))))
        help_keys[k.lower()] = title

with open(os.path.join(OUT, "help-topics.csv"), "w", encoding="utf-8-sig", newline="") as f:
    w = csv.writer(f)
    w.writerow(["file", "key", "h1_title", "text_chars"])
    w.writerows(help_rows)

# headings used in hyper.xml bodies (structure of a help popup)
hyper = open(os.path.join(HELP, "hyper.xml"), encoding="utf-8", errors="replace").read()
h2 = collections.Counter(plain(x) for x in re.findall(r"<(?:H2|H3|b)>(.*?)</(?:H2|H3|b)>", hyper, re.S | re.I))
L.append("\nMost frequent bold/H2/H3 sub-headings inside hyper.xml help popups (shows the recurring help-article shape):\n")
for t, c in h2.most_common(80):
    if t and len(t) >= 4 and t[0].isupper():
        L.append("- %s (%d)" % (t[:90], c))

# hyper.xml H1 title shapes
titles = [t for fn, k, t, n in help_rows if fn == "hyper.xml" and t]
pat = collections.Counter()
for t in titles:
    tl = t.lower()
    for p in ["what is", "what are", "what's", "why ", "how ", "where ", "when ", "who ", "do i", "can i",
              "should i", "more info", "about "]:
        if tl.startswith(p):
            pat[p.strip()] += 1
            break
    else:
        pat["(noun phrase / other)"] += 1
L.append("\nhyper.xml popup titles by opening words (%d titled entries):\n" % len(titles))
for p, c in pat.most_common():
    L.append("- `%s`: %d (%.0f%%)" % (p, c, 100.0 * c / len(titles)))
L.append("\nExamples: " + "; ".join('"%s"' % t for t in titles[100:112]))

# ------------------------------------------------ link resolution
sp = os.path.join(OUT, "screens.jsonl")
if os.path.exists(sp):
    S = [json.loads(l) for l in open(sp, encoding="utf-8")]
    targets = collections.Counter()
    labels = collections.Counter()
    for s_ in S:
        for l_ in s_["links"]:
            label, _, tgt = l_.rpartition(" -> ")
            targets[tgt] += 1
            labels[label] += 1
    res = sum(1 for t in targets if ("hyp" + t).lower() in help_keys)
    L.append("\n## In-screen help links\n")
    L.append("%d distinct link targets appear in the decoded screens; %d (%.0f%%) resolve to a `hyper.xml` "
             "entry `hyp<target>` (the rest point at FAQ/screen popups `scr*`, dialogs or URLs)." %
             (len(targets), res, 100.0 * res / max(1, len(targets))))
    pre = collections.Counter((re.match(r"[A-Za-z]*", t).group(0) or t[:4])[:8] for t in targets)
    L.append("\nTarget-name prefixes (distinct targets): " + ", ".join("`%s` %d" % kv for kv in pre.most_common(15)))
    L.append("\nMost frequent link labels:\n")
    for t, c in labels.most_common(25):
        L.append("- \"%s\" (%d)" % (t, c))

# ------------------------------------------------ images
files = sorted(os.listdir(IMG))
ext = collections.Counter(os.path.splitext(f)[1].lower() for f in files)
L.append("\n## UI images (`64bit/local/img`)\n")
L.append("%d files: %s.\n" % (len(files), ", ".join("%s %d" % (e or "(none)", c) for e, c in ext.most_common())))
fam = collections.Counter()
groups = collections.defaultdict(list)
for f in files:
    b = os.path.splitext(f)[0]
    m = re.match(r"(?i)(intgfx|icn|interviewgraphic|icon|img|spacer|logo|warning|btn)[_-]?(.*)", b)
    if m:
        fam[m.group(1).lower()] += 1
        sub = re.split(r"[_-]", m.group(2) or "x")[0].lower() or "x"
        groups[(m.group(1).lower(), sub)].append(b)
    else:
        fam["(other)"] += 1
L.append("Families by filename prefix: " + ", ".join("`%s` %d" % kv for kv in fam.most_common()) + "\n")
L.append("`intgfx_*` (interview graphics) and `icn_*` sub-families with 4+ files:\n")
L.append("| family | sub-family | files | examples |\n|---|---|---|---|")
for (fa, sub), v in sorted(groups.items(), key=lambda kv: -len(kv[1])):
    if len(v) >= 4 and fa in ("intgfx", "icn", "interviewgraphic"):
        L.append("| %s | %s | %d | %s |" % (fa, sub, len(v), ", ".join(v[:4])))
L.append("\nReading of the families: `intgfx_state(s)_*` state maps/badges (state product), `intgfx_landing_*` the "
         "hub landing-table row icons (income / deductions categories), `intgfx_ef_*` e-file status art, "
         "`intgfx_upsell_*` and `intgfx_comparison_*` edition-upgrade art, `intgfx_auditriskmeter_*` the audit-risk "
         "gauge, `intgfx_progressbar_*` / `intgfx_tab_*` navigation chrome, `intgfx_refund_*` refund-meter art, "
         "`intgfx_pi_*` / `intgfx_pisummary_*` personal-info summary art, `icn_*sectionOpener*` 1x/2x/3x section "
         "opener illustrations, `icn_xsell_*` cross-sell (QuickBooks, payments, MyCorp).")

# ------------------------------------------------ dialogs
L.append("\n## Dialog pages (`64bit/local/dlg`)\n")
for f in sorted(os.listdir(DLG)):
    if f.endswith(".htm"):
        t = open(os.path.join(DLG, f), encoding="utf-8", errors="replace").read()
        tt = re.search(r"<title>(.*?)</title>", t, re.S | re.I)
        body = plain(t)[:160]
        L.append("- `%s` - %s%s" % (f, ("title \"%s\"; " % tt.group(1).strip()) if tt else "", body))

open(os.path.join(OUT, "assets-summary.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print("help entries:", len(help_rows), "images:", len(files))
