// ============================================================================
//  Generates: C:\us-tax\XLS\computations\1i.xlsx
//  Source-of-truth references:
//    - lines/1i.md (authoritative spec)
//    - dependencies/1i.md
//    - knowledge/line-1i-combat-pay.md
//    - flowcharts/1i.drawio
//    - diagrams/1i.drawio
//    - TaxReturnComputeService.computeCombatPay() lines 10219-10264
//    - ReferenceData.java (no line-1i-specific constants — line 1i is a passthrough)
//    - IRS 2025 Form 1040 instructions (i1040gi_2025.pdf): "elect to include nontaxable combat pay
//      in figuring your EIC, enter the amount on Form 1040 or 1040-SR, line 1i"
//    - IRS Pub. 3 (Armed Forces' Tax Guide), 2024 revision; Pub. 596 (EIC); Pub. 590-A (IRA)
//    - W-2 box 12 code Q is THE sole source field
//
//  Tax year: 2025
// ============================================================================

const XLSX = require('xlsx');
const path = require('path');
const fs = require('fs');

const OUTPUT = path.join(__dirname, '..', 'computations', '1i.xlsx');
fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });

const wb = XLSX.utils.book_new();

// ─── Sheet 1: Main Computation ────────────────────────────────────────────
const main = [
  ['LINE 1i — NONTAXABLE COMBAT PAY ELECTION'],
  ['Tax Year', '2025'],
  ['Form / Line', 'Form 1040 / 1040-SR, line 1i'],
  ['Concept', 'Optional election to include nontaxable combat pay in EARNED INCOME for the EIC and Additional Child Tax Credit (ACTC) WITHOUT making the combat pay taxable. Does NOT enter line 1z, AGI, or wages.'],
  ['Per-Return Formula', 'line1i = roundMoney( addNonNull(taxpayerElected, spouseElected) )'],
  ['Per-Person Formula', 'electedAmount_p = electCombatPay_p ? (totalCodeQ_p ?? 0) : null'],
  ['Filed', 'Direct entry on Form 1040 line 1i. NO separate election form (the IRS removed the prior "NCP" notation requirement). The election IS the line 1i value.'],
  ['Backend method', 'TaxReturnComputeService.computeCombatPay() lines 10219-10264'],
  ['Output', 'form1040.income.nontaxableCombatPayElection (BigDecimal; null when neither person elects, 0 when elected with no code Q W-2)'],
  ['IRS source', 'IRS 2025 Form 1040 instructions (line 1i note); Pub. 3 (Armed Forces); Pub. 596 (EIC); Schedule 8812 instructions (ACTC earned-income floor)'],
  [],
  ['STEP-BY-STEP COMPUTATION'],
  ['Step', 'Computation', 'Notes'],
  [1, 'Load taxpayer + spouse identification', 'taxpayerSsn = normalize(you.ssn); spouseSsn = normalize(spouse.ssn). On MFS, the spouse form is normally absent — but if stale `combat-pay-spouse` data exists from a prior MFJ year, the current code processes it (see Code Validation #1).'],
  [2, 'Load W-2 entries from statement service', 'Statement service returns ALL W-2 entries for the user; combat pay code Q amounts must be filtered by employeeSSN to attribute correctly to taxpayer vs spouse.'],
  [3, 'Compute per-person code Q totals', 'taxpayerTotal = sumW2Box12ByCodes(w2Entries, {"Q"}, taxpayerSsn)\nspouseTotal = sumW2Box12ByCodes(w2Entries, {"Q"}, spouseSsn)\n\nIMPORTANT: sumW2Box12ByCodes with a NULL ssn parameter sums ALL entries regardless of attribution (line 10897 — `if (hasText(normalizedSsn))` skips the filter when ssn is empty). If you.ssn is null in production, taxpayer would absorb spouse amounts (Code Validation #4).'],
  [4, 'Read per-person election flag', 'electTaxpayer = combat-pay-taxpayer.electCombatPay\nelectSpouse   = combat-pay-spouse.electCombatPay\n\nNull or false → no election. Boolean.TRUE.equals(...) is the gate (line 10237/10240).'],
  [5, 'Apply all-or-none rule per person', 'taxpayerElected = electTaxpayer == true ? (taxpayerTotal ?? 0) : null\nspouseElected   = electSpouse   == true ? (spouseTotal   ?? 0) : null\n\nKey design choice: when elected but no code Q exists, the result is BigDecimal.ZERO (not null) — per spec §10.4 "if electCombatPay = true but no code Q W-2 entries match, the elected amount is 0 (not null)".'],
  [6, 'Sum per-return value with null-aware addition', 'line1iRaw = addNonNull(taxpayerElected, spouseElected)\n\naddNonNull semantics: null + null = null; null + X = X; X + Y = X+Y. So when neither elects, line 1i is null. When taxpayer elects $0 (no Q) and spouse elects nothing, line 1i = 0 (not null).'],
  [7, 'Round to whole dollars', 'line1i = roundMoney(line1iRaw)\n\nWhole-dollar HALF_UP rounding (per ROUNDING_MODE constant). BigDecimal scale is 0.'],
  [8, 'Persist on form1040.income', 'income.setNontaxableCombatPayElection(line1i)\n\nOnly stored when non-null. The framework omits null fields from JSON output, so an absent line 1i means "no election" rather than "$0".'],
  [],
  ['MUTUAL EXCLUSION RULES (enforced by code or spec)'],
  ['Rule', 'Implementation', 'Why'],
  ['Per-person all-or-none', 'electCombatPay is a boolean; UI offers no "partial amount" entry. When elected, the FULL code Q total is included; when not elected, nothing.', 'IRS rule (Pub. 596): "If you elect to include nontaxable combat pay in earned income, all of your nontaxable combat pay must be included." Partial inclusion is not allowed.'],
  ['MFJ spouses elect independently', 'Two separate forms (combat-pay-taxpayer / combat-pay-spouse), each with its own electCombatPay flag.', 'IRS rule (Pub. 596): all four MFJ combinations are valid (T-only, S-only, both, neither). Each spouse may make their own election.'],
  ['Line 1i is NOT taxable wages', 'Line 1i is computed and stored separately from getTotalWages(). Line 1z = sum(1a..1h) ONLY (line 4137 of TaxReturnComputeService.java; explicitly commented).', 'Combat pay is excluded from gross income under IRC §112. Line 1i is a CREDIT-WORKSHEET earned-income marker, not income for tax purposes. Adding it to line 1z would erroneously increase AGI.'],
  ['Line 1i is NOT in AGI', 'AGI (line 11b) = line 9 - line 10. Line 9 = line 1z + 2b + 3b + 4b + 5b + 6b + 7a + 8. Line 1i is excluded from line 1z, hence from line 9, hence from AGI.', 'Same reason as above. The election keeps the income tax-free while granting credit access.'],
  ['Code Q only — no other W-2 codes contribute', 'COMBAT_PAY_CODES = Set.of("Q") (line 121).', 'IRS rule (Pub. 3): only nontaxable pay reported in W-2 box 12 with code Q is treated as combat pay for earned-income purposes. BAH/BAS/military allowances, pre-tax deductions, etc. are NOT combat pay even if also nontaxable.'],
  ['Officer cap reflected by issuer (W-2)', 'Backend reads W-2 box 12 code Q amount as-given; no officer-cap recalculation.', 'Per IRC §112(b), commissioned officers receive a LIMITED exclusion (capped at the highest enlisted basic pay rate plus hostile-fire pay). The W-2 issuer applies the cap before reporting code Q. Backend trusts the issuer-reported value.'],
  ['No-code-Q + elected = $0 (NOT null)', 'taxpayerElected = electTaxpayer == true ? (taxpayerTotal == null ? BigDecimal.ZERO : taxpayerTotal) : null', 'Per spec §10.4 — distinguishes "user explicitly elected with no Q" from "user did not elect". Allows the ACTC/EIC worksheets to see a deliberate "0" rather than treating the field as absent.'],
  [],
  ['DECISION TREE — what enters line 1i?'],
  ['Path', 'Code Q total', 'electCombatPay', 'Result on line 1i'],
  ['Taxpayer', 'present', 'true', 'taxpayerTotal'],
  ['Taxpayer', 'present', 'false / null', '0 (this person contributes null; addNonNull keeps the other side)'],
  ['Taxpayer', 'null (no Q)', 'true', '0 (null → ZERO; design choice)'],
  ['Taxpayer', 'null (no Q)', 'false / null', 'null (no contribution)'],
  ['Spouse', '(same matrix as taxpayer, applied to spouse SSN-attributed totals)', '', ''],
  ['Per-Return', '— ', '—', 'addNonNull(taxpayerElected, spouseElected); roundMoney; either null or a non-negative integer.'],
  [],
  ['DOWNSTREAM CREDIT EFFECT — EIC and ACTC'],
  ['Path', 'How line 1i is used', 'IRS reference'],
  ['Earned Income Credit (line 27a)', 'earnedIncomeForEic = normalEarnedIncome + line1i. EIC is then looked up in the EIC table using the LESSER of earnedIncomeForEic or AGI at the phaseout threshold. Combat pay raises earned income but NOT AGI — net effect depends on whether the filer is in the EIC phase-in (beneficial) or phaseout (potentially detrimental) range.', 'IRS Pub. 596 (Earned Income Credit), 2025 EIC worksheets. NOTE: current code (TaxReturnComputeService.computeLine27aEIC line 16599) uses the EIC personal form\'s OWN `electNontaxableCombatPay` flag and re-sums code Q — see Code Validation #2.'],
  ['ACTC — Schedule 8812 Part II-A', 'Line 18a = totalWages + line1i (combat pay disclosure on line 18b). Line 19 = max(0, line18a - $2,500). Line 20 = line19 × 15%. Cap per qualifying child = $1,700 (2025).', 'IRS Schedule 8812 instructions, 2025. Wired correctly at TaxReturnComputeService line 19087-19096 — uses `form1040.getIncome().getNontaxableCombatPayElection()` directly (consistent source).'],
  ['IRA contribution compensation (Pub. 590-A)', 'Nontaxable combat pay counts as compensation for IRA-contribution purposes (statutory exception). NOT a line-1i math path — handled in Form 8606 / IRA deduction logic separately.', 'IRC §219(f)(7); Pub. 590-A Section 2. Out of scope for line 1i; verification deferred (Code Validation #7 / outstanding.md).'],
];

const ws1 = XLSX.utils.aoa_to_sheet(main);
ws1['!cols'] = [{ wch: 22 }, { wch: 75 }, { wch: 90 }];
XLSX.utils.book_append_sheet(wb, ws1, 'Main Computation');

// ─── Sheet 2: Inputs ──────────────────────────────────────────────────────
const inputs = [
  ['INPUTS — Every Field That Feeds Line 1i'],
  ['Sourced from C:\\us-tax\\XLS\\input_forms\\*.xlsx (post-2026-05-10 generator regen).'],
  [],
  ['#', 'Source xlsx', 'Field path / model key', 'Label / W-2 box', 'Required?', 'Role in line 1i compute', 'Cross-references'],
  [1, 'form-combat-pay-taxpayer.xlsx (Income → Combat Pay → Taxpayer tab)', 'taxpayerCombatPay.electCombatPay', 'Include combat pay as earned income for EITC', 'YES (boolean — null/false = no election)', 'Step 4: drives whether taxpayer\'s code Q amounts flow into line 1i. The single user-facing election control.', 'YAML: 1i-combat-pay-taxpayer.yaml; lines/1i.md §10 "All-or-none enforcement"'],
  [2, 'form-combat-pay-taxpayer.xlsx', 'taxpayerCombatPay.combatPayTotal', 'Taxpayer nontaxable combat pay (W-2 Box 12 Code Q)', 'NO — read-only display', 'Snapshot of code Q sum at UI save-time. Backend RECOMPUTES from W-2 statements (does NOT trust this field). Persisted only for UI render speed.', 'form-combat-pay-taxpayer.xlsx row 1 (readOnly:true)'],
  [3, 'form-combat-pay-spouse.xlsx (Income → Combat Pay → Spouse tab)', 'spouseCombatPay.electCombatPay', 'Include combat pay as earned income for EITC', 'NO on non-MFJ; YES on MFJ if spouse has code Q', 'Step 4: drives whether spouse\'s code Q amounts flow into line 1i.', 'YAML: 1i-combat-pay-spouse.yaml'],
  [4, 'form-combat-pay-spouse.xlsx', 'spouseCombatPay.combatPayTotal', 'Spouse nontaxable combat pay (W-2 Box 12 Code Q)', 'NO — read-only display', 'Snapshot only; backend recomputes.', ''],
  [],
  ['STATEMENT INPUTS — W-2 Box 12'],
  [5, 'form-w-2.xlsx (Statements → W-2)', 'box12Entries[].code (item.code)', 'W-2 Box 12 letter code', 'YES — must equal "Q" (case-handled by Set.of("Q"))', 'Step 3: filters the box12 array; only entries with code = "Q" contribute. COMBAT_PAY_CODES = Set.of("Q").', 'TaxReturnComputeService.java:121; W-2 instructions box 12 reference'],
  [6, 'form-w-2.xlsx', 'box12Entries[].box12Amount (item.box12Amount)', 'W-2 Box 12 dollar amount', 'YES per qualifying entry', 'Step 3: summed via sumW2Box12ByCodes.', 'IRS W-2 instructions box 12 (Code Q definition)'],
  [7, 'form-w-2.xlsx', 'employeeSSN (model.employeeSSN)', 'W-2 Box (a) employee SSN', 'YES — drives attribution to taxpayer vs spouse', 'Step 3: SSN-filter. normalizeSsn (digits-only) is applied to BOTH the W-2 SSN and the personal-form SSN before comparison. When ssn is null, sumW2Box12ByCodes SUMS ALL entries (Code Validation #4).', 'TaxReturnComputeService.sumW2Box12ByCodes line 10897'],
  [],
  ['IDENTITY INPUTS — Per-Person SSN'],
  [8, 'form-identification-taxpayer.xlsx (Personal → Identification → Taxpayer)', 'taxpayerIdentity.ssn', 'Taxpayer SSN (Box (a) on Form 1040)', 'YES — without it, taxpayer code Q attribution fails', 'Step 1: read by `getString(you, "ssn")` after PersonalDataService normalizes form IDs. UI saves to identification-taxpayer; backend reads from `you` form (legacy alias).', 'form-identification-taxpayer.xlsx row 4'],
  [9, 'form-identification-spouse.xlsx (Personal → Identification → Spouse)', 'spouseIdentity.spouseSsn', 'Spouse SSN', 'YES on MFJ; NO on MFS (spouse normally absent)', 'Step 1: backend reads `getString(spouse, "ssn")` — but the modern UI form populates `spouseSsn`, NOT `ssn`. See Code Validation #3 for the mismatch.', 'form-identification-spouse.xlsx row 4 (spouseSsn)'],
  [],
  ['FILING STATUS (used by spec for MFS gating, not yet by code — see Code Validation #1)'],
  [10, 'form-filing-status.xlsx', 'filingStatus', 'Filing status', 'YES', 'Currently UNUSED by computeCombatPay — but should drive an isMfsReturn guard (mirrors line 1c/1d/1e/1f/1g/1h pattern). On MFS, spouse-side election + code Q must be excluded.', 'form-filing-status.xlsx; Code Validation #1'],
];

const ws2 = XLSX.utils.aoa_to_sheet(inputs);
ws2['!cols'] = [{ wch: 4 }, { wch: 50 }, { wch: 50 }, { wch: 55 }, { wch: 30 }, { wch: 90 }, { wch: 60 }];
XLSX.utils.book_append_sheet(wb, ws2, 'Inputs');

// ─── Sheet 3: Reference Data / Constants ──────────────────────────────────
const constants = [
  ['REFERENCE DATA — Constants Used by Line 1i (sparse — line 1i is a passthrough)'],
  ['Line 1i has NO ReferenceData.java entries because it is a pure passthrough. The ONLY relevant constant is the W-2 box 12 code letter "Q". Officer caps are applied at the W-2-issuer level and not re-derived in this code.'],
  [],
  ['Constant', 'Value', 'Source', 'Used by line 1i?', 'Notes'],
  [],
  ['Line-1i direct constants'],
  ['COMBAT_PAY_CODES', 'Set.of("Q")', 'TaxReturnComputeService.java:121', 'YES — Step 3', 'IRS W-2 instructions: code Q = "Nontaxable combat pay (see EIC instructions)". Stable across years; does not change with COLA.'],
  [],
  ['Downstream-credit constants (NOT used by line 1i directly; shown for context only)'],
  ['ACTC_EARNED_INCOME_FLOOR', '$2,500', 'Hard-coded inline at TaxReturnComputeService.java:19098 (`new BigDecimal("2500")`)', 'NO (Schedule 8812 Part II-A consumer)', '2025 ACTC: line19 = max(0, line18a - $2,500). The floor has been $2,500 since 2018 (TCJA). Should be in ReferenceData.java but is not (separate gap, out of scope for line 1i audit).'],
  ['ACTC_RATE', '15%', 'Hard-coded inline at TaxReturnComputeService.java:19103 (`new BigDecimal("0.15")`)', 'NO', 'line20 = line19 × 15%. Stable; same constant since 2018.'],
  ['ACTC_PER_CHILD_CAP', '$1,700', 'ReferenceData.java (per Schedule 8812 audit)', 'NO', '2025 cap. Indexed; was $1,600 for 2023, $1,700 for 2024-2025.'],
  ['EIC_INVESTMENT_INCOME_CEILING_2025', '$11,950', 'ReferenceData.INVESTMENT_INCOME_CEILING_EIC_2025', 'NO (EIC consumer)', '2025 EIC investment-income disqualification ceiling. COLA-indexed. Does not affect line 1i.'],
  [],
  ['Officer cap — issuer-applied, not in ReferenceData.java'],
  ['Highest enlisted basic pay rate', 'Varies by month and rank; published by DFAS', 'IRS Pub. 3 §1; DoD Military Pay tables', 'NO — not consumed', 'Per IRC §112(c), commissioned officers receive a LIMITED combat pay exclusion (capped at the highest rate of enlisted basic pay, plus hostile-fire/imminent-danger pay). The W-2 issuer applies the cap before reporting code Q box 12 amount; the recipient receives the already-limited amount on the W-2.'],
  ['Hostile-fire / imminent-danger pay', '$225/month (2025)', 'DoD pay tables; 37 USC §310', 'NO — not consumed', 'Added on top of the enlisted-basic-pay cap for officer exclusion. Same source-of-truth pattern: applied by issuer.'],
  [],
  ['Statutory references (IRS rules, not configurable constants)'],
  ['IRS rule', 'Citation', 'Notes'],
  ['Combat pay tax exclusion', 'IRC §112', 'Enlisted/warrant officers: full exclusion. Commissioned officers: capped at highest enlisted basic pay + hostile-fire pay.'],
  ['Combat pay election for EIC', 'IRC §32(c)(2)(B)(vi); Pub. 596', 'Election permits including nontaxable combat pay in EIC earned income. All-or-none per spouse.'],
  ['Combat pay for ACTC', 'IRC §24(d); Schedule 8812 Part II-A line 18b disclosure', 'Combat pay is included in earned income for ACTC 15% floor calculation.'],
  ['Combat pay as IRA compensation', 'IRC §219(f)(7); Pub. 590-A', 'Nontaxable combat pay counts as IRA contribution compensation. Out of scope for line 1i math.'],
  ['No "NCP" notation requirement (post-2023)', 'IRS update to Pub. 3 (2023 revision)', 'Prior IRS guidance asked filers to write "NCP" on Form 1040 alongside the elected amount. The 2023 revision removed that requirement; populating line 1i IS the election.'],
];
const ws3 = XLSX.utils.aoa_to_sheet(constants);
ws3['!cols'] = [{ wch: 50 }, { wch: 30 }, { wch: 60 }, { wch: 35 }, { wch: 80 }];
XLSX.utils.book_append_sheet(wb, ws3, 'Reference Data');

// ─── Sheet 4: Side-Effect Outputs ─────────────────────────────────────────
const sideEffects = [
  ['SIDE-EFFECT OUTPUTS — Line 1i Has NO Directly-Attached Form/Schedule'],
  ['Line 1i is a single Form 1040 cell. No separate IRS form is filed for the election (the IRS removed the "NCP" notation requirement in the 2023 revision of Pub. 3). The election IS the line 1i value itself.'],
  ['However, line 1i is consumed downstream by two credit computations and one disclosure line on Schedule 8812. Each consumer is documented below.'],
  [],
  ['Output target', 'Where wired', 'Effect'],
  ['Form 1040 line 1i (the cell itself)', 'TaxReturnComputeService.buildIncome(); income.setNontaxableCombatPayElection(line1i)', 'Persisted on form1040.income only when non-null. Whole-dollar HALF_UP rounding. Stored to Firestore via TaxReturnDataService.'],
  ['Schedule 8812 line 18a / 18b (ACTC earned income disclosure)', 'TaxReturnComputeService.computeSchedule8812() lines 19087-19096', 'line18a = totalWages + line1i; line18b = line1i (disclosure of the combat-pay component). IRS Schedule 8812 line 18b explicitly asks the taxpayer to identify how much of line 18a came from nontaxable combat pay. Wired CORRECTLY using `form1040.getIncome().getNontaxableCombatPayElection()` (consistent source-of-truth path).'],
  ['EIC earned income (line 27a worksheet)', 'TaxReturnComputeService.computeLine27aEIC() line 16599-16611', 'WIRED INCONSISTENTLY: instead of reading `form1040.income.nontaxableCombatPayElection`, the EIC code reads its OWN `electNontaxableCombatPay` flag from the EIC personal form AND re-sums W-2 box 12 code Q. Same source data, but TWO separate user-facing election questions create a divergence risk. See Code Validation #2.'],
  ['IRA contribution compensation', '(NOT wired in current code — informational)', 'Per IRC §219(f)(7), nontaxable combat pay counts as compensation for IRA contributions. Form 8606 / IRA deduction logic should consider it but currently does NOT. Out of scope for line 1i; logged as a verification item under Code Validation #7.'],
  [],
  ['No PDF appended-page output for line 1i'],
  ['Unlike line 1h (which appends a "Refer to attached sheet" page when the statement text is long), line 1i is a single dollar amount with no statement requirement. The 2023 IRS update removed the "NCP" notation requirement.'],
  [],
  ['No advisory or blocking flag emitted by line 1i'],
  ['Per spec §13 invariants, line 1i never produces a flag. If the user has no code Q, the field stays null/zero silently. The UI handles the "no code Q" message client-side; the backend does not emit a flag.'],
];
const ws4 = XLSX.utils.aoa_to_sheet(sideEffects);
ws4['!cols'] = [{ wch: 60 }, { wch: 70 }, { wch: 100 }];
XLSX.utils.book_append_sheet(wb, ws4, 'Side-Effect Outputs');

// ─── Sheet 5: Validation Flags ────────────────────────────────────────────
const flags = [
  ['VALIDATION FLAGS — Line 1i Emits NONE'],
  ['Per spec §13 (Invariants) and current code (computeCombatPay lines 10219-10264), line 1i NEVER emits a TaxReturnFlag. This sheet documents the explicit "no flags" design and the rationale, plus what the UI handles client-side.'],
  [],
  ['Flag scenario considered', 'Why no flag is emitted', 'Where the user-side message lives'],
  ['Election made but no code Q W-2 found for that person', 'Spec §10.4: "if electCombatPay = true and no code Q W-2 → result is 0, not null". Treated as a deliberate $0 election; no warning emitted by backend.', 'UI: form-combat-pay-taxpayer/spouse component disables the dropdown and shows: "No W-2 Box 12 code Q combat pay was found for the [taxpayer/spouse]." See line spec §10.4.'],
  ['No election made (electCombatPay = null/false)', 'Default state — line 1i is null. No user action required, no flag.', 'Implicit; UI shows the election dropdown enabled when code Q exists.'],
  ['Stale spouse election on MFS return', 'Currently NOT GUARDED (Code Validation #1). Spouse-side election processes regardless of filing status. The UI normally hides the spouse form on non-MFJ returns, but if `combat-pay-spouse` data was saved on a prior MFJ year and the user changed to MFS, the data still influences line 1i.', 'No flag today. Should be guarded by an isMfsReturn parameter mirroring lines 1c-1h. See Code Validation #1.'],
  ['Officer code Q amount exceeds plausible cap', 'No backend recalculation — the W-2 issuer applied the IRC §112(c) officer cap. Backend trusts the issuer-reported value.', 'No UI message; relies on W-2 source.'],
  ['Line 1i exceeds taxable wages on the return', 'No invariant — combat pay is NONTAXABLE, so it can exceed taxable wages without anomaly (e.g., a deployed servicemember whose entire pay is excludable).', 'No flag; this is normal.'],
  ['Multiple W-2s with code Q for same person', 'Summed correctly via sumW2Box12ByCodes (which iterates all W-2s and accumulates).', 'No flag; correct behavior.'],
  ['Code Q with $0 amount', 'Summed as 0; if elected, line 1i = 0 (not null).', 'No flag; correct behavior.'],
  [],
  ['Contrast: line 1c, 1d, 1e, 1f, 1g, 1h all DO emit blocking flags. Line 1i is unique among the 1a-1h-1i set in emitting nothing.'],
  ['This is intentional — line 1i is purely an OPTIONAL ELECTION, not a required computation. There is no scenario where the return cannot be filed because of line 1i state.'],
];
const ws5 = XLSX.utils.aoa_to_sheet(flags);
ws5['!cols'] = [{ wch: 60 }, { wch: 90 }, { wch: 60 }];
XLSX.utils.book_append_sheet(wb, ws5, 'Validation Flags');

// ─── Sheet 6: Code Validation ─────────────────────────────────────────────
const codeIssues = [
  ['CODE VALIDATION — Discrepancies, Bugs, and Missing Pieces'],
  ['Reviewed against: TaxReturnComputeService.computeCombatPay() lines 10219-10264, computeLine27aEIC() lines 16596-16611 (EIC consumer), computeSchedule8812() lines 19087-19096 (ACTC consumer), Form 1040 line 1z formula at line 4136-4138, sumW2Box12ByCodes() lines 10887-10925, ReferenceData.java (no line-1i constants), W-2 input xlsx, knowledge file naming convention (verified 2026-05-10).'],
  ['LINE 1i AUDIT COMPLETE 2026-05-10 — All 10 issues closed. Outcomes: 1 defensive bug fix (#1 MFS guard cascade — 7th line); 1 correctness/source-of-truth refactor (#2 EIC reads form1040.income.nontaxableCombatPayElection, removing the duplicate election-flag divergence risk); 2 audit-false-positive verifications with lock-in tests (#3 SSN overlay via resolveSpouseIdentification, #9 line 1z exclusion); 1 defensive Option-A guard (#4 hasText null-SSN protection at the two combat-pay sum sites); 1 coverage-gap closure (+7 unit tests for #5); 1 knowledge-file rename (#6 line-1i-combat-pay.md); 2 deferred-enhancement closures with outstanding.md entries (#7 IRC §219(f)(7) combat-pay-as-IRA-compensation; #8 Form 1040 top combat_zone checkbox wiring); 1 verified-correct closure with multi-test breadcrumb (#10 all-or-none per-person ternary). Backend regression: 741/741 pass (was 730 — net +11 unit tests). Four new deferred-advisory entries added to outstanding.md (Option-C broader helper cleanup, legacy EIC YAML field deprecation, IRA compensation §219(f)(7), top combat_zone checkbox). Three inline comment chains added/extended at computeCombatPay covering Issues #1/#3/#4/#10, plus one at the line 1z formula covering Issue #9.'],
  [],
  ['#', 'Severity', 'Issue', 'Where Found', 'Recommended Fix'],
  [1, 'DEFENSIVE GAP — MFS GUARD NOT IN ORCHESTRATOR — RESOLVED 2026-05-10', 'Pre-fix: computeCombatPay read spouseSsn unconditionally and processed both `combat-pay-spouse` form data and spouse-attributed code Q W-2s regardless of filing status. On MFS with stale `combat-pay-spouse` data (e.g., from a prior MFJ year), spouse contribution leaked into the taxpayer\'s line 1i. Same pattern as line 1c #1, 1d #1, 1e #2, 1f #2, 1g #1, 1h #1. Post-fix: (1) added `boolean isMfsReturn` parameter to computeCombatPay; (2) call site at line 378 updated to pass isMfsReturn (cluster with computeDependentCareBenefits/computeAdoptionBenefits/computeOtherEarnedIncome which already accept it); (3) inside the method, three spouse reads gated explicitly on isMfsReturn — `String spouseSsn = isMfsReturn ? null : ...`, `Boolean electSpouse = isMfsReturn ? null : ...`, `BigDecimal spouseTotal = isMfsReturn ? null : sumW2Box12ByCodes(...)`. Three-point gate is more explicit than the line-1h two-point gate because sumW2Box12ByCodes(_, _, null) sums ALL entries (Issue #4) — gating only spouseSsn would not have prevented the leak. With three gates, on MFS spouseTotal=null + electSpouse=null → existing all-or-none ternary returns null → addNonNull(taxpayerElected, null) yields taxpayer-only contribution. Lock-in test `mfsExcludesSpouseCombatPayElectionFromLine1i` added — MFS return with taxpayer code Q $1,500 + electCombatPay=true + STALE spouse code Q $1,200 + STALE combat-pay-spouse.electCombatPay=true → asserts line 1i = $1,500 (NOT $2,700 aggregated). **Single-guard MFS cascade now applied to 7 lines** (1c, 1d, 1e, 1f, 1g, 1h, 1i). Backend regression: 731/731 pass.', 'TaxReturnComputeService.computeCombatPay lines 10219-10269 (signature + body); call site in prepare() at line 378; test mfsExcludesSpouseCombatPayElectionFromLine1i', 'CLOSED. Three-point gate variant of the single-guard cascade (vs line-1h two-point) chosen because sumW2Box12ByCodes lacks defensive null-SSN handling (Issue #4 — separate fix).'],
  [2, 'CORRECTNESS / DUPLICATION — EIC HAS ITS OWN COMBAT-PAY ELECTION FLAG — RESOLVED 2026-05-10', 'Pre-fix: computeLine27aEIC at lines 16604-16617 read its own `electNontaxableCombatPay` and `spouseElectNontaxableCombatPay` flags from the EIC personal form AND re-summed W-2 box 12 code Q via sumW2Box12ByCodes — instead of using `form1040.income.nontaxableCombatPayElection`. Two separate user-facing election questions created a divergence risk: a user could elect "Yes" on the line-1i form but "No" on the EIC form (or vice versa), producing inconsistent earned-income calculations across line 1i, ACTC (Schedule 8812 line 18a/18b), and EIC (line 27a). Post-fix: refactored computeLine27aEIC to read `form1040.getIncome().getNontaxableCombatPayElection()` as the single source of truth — same pattern as Schedule 8812 at line 19091. Result: one election question (on the line-1i / Combat Pay form), one computed value, three consumers (line 1i display, Schedule 8812 line 18, EIC line 27a) all reading the same field. (1) Existing test `line27aCombatPayElection_addsToEarnedIncome` updated to set the election via `combat-pay-taxpayer.electCombatPay` instead of `eicForm.electNontaxableCombatPay` — same $649 plateau outcome via the unified path. (2) New lock-in test `line27aEicReadsCombatPayFromLine1iSource_notEicFormFlag` (two-part) asserts (Part A) line-1i election alone produces $649; (Part B) legacy EIC flag alone with line-1i election OFF produces $306 — proving the legacy flag has NO effect after refactor. (3) Legacy YAML/UI cleanup deferred to outstanding.md ("Line 27a EIC — Deprecate Legacy electNontaxableCombatPay YAML/UI Fields", ~10-15 min if revisited). Backend regression: 732/732 pass.', 'TaxReturnComputeService.computeLine27aEIC lines ~16604-16612 (now reads form1040.getIncome().getNontaxableCombatPayElection() directly); tests line27aCombatPayElection_addsToEarnedIncome (updated) + line27aEicReadsCombatPayFromLine1iSource_notEicFormFlag (new)', 'CLOSED. Single source of truth now matches the Schedule 8812 pattern. Legacy YAML fields remain in `27a-earned-income-credit-{taxpayer,spouse}.yaml` and corresponding Angular components — backend ignores them; UI cleanup deferred to outstanding.md.'],
  [3, 'POTENTIAL DATA-MISS — SPOUSE SSN READ FROM LEGACY FORM — AUDIT FALSE POSITIVE; VERIFIED CORRECT 2026-05-10', 'Pre-fix concern: computeCombatPay reads `getString(spouse, "ssn")` but modern UI uses `identification-spouse.spouseSsn`. Audit framed this as a potential data-miss bug. Verification: the `spouse` map passed into computeCombatPay is NOT the raw `personalForms.get("spouse")` — it is the RESOLVED output of `resolveSpouseIdentification(legacySpouse, identificationSpouse)` invoked at line 151 of TaxReturnComputeService. That resolver calls `overlayResolvedField(resolved, identificationSpouse, "ssn", "spouseSsn")` at line 3902, which copies `identification-spouse.spouseSsn` into the resolved `spouse.ssn` slot BEFORE computeCombatPay runs. Same overlay handles taxpayer side (line 3870 — `you.ssn` from `identification-taxpayer.ssn`). The original code is correct; the audit author missed the overlay because it is invisible at the call site. Closure: layered audit-false-positive protection. (1) Eight-line breadcrumb comment added at computeCombatPay just below the LOG.infof, naming `resolveSpouseIdentification` + the line 3902 overlay, citing audit ID + verification date, listing the lock-in test name. Future reviewers can trace the implicit dependency in two reads instead of running a full investigation. (2) New lock-in test `combatPayUsesSpouseSsnFromIdentificationSpouseFormViaOverlay` — MFJ with spouse SSN ONLY in identification-spouse.spouseSsn (no legacy `spouse.ssn`), spouse code Q $1,200, electCombatPay=true → asserts line 1i = $1,200. Non-trivial protection: the call site has NO visible dependency on the overlay, so an accidental removal of the resolver would silently break combat-pay attribution; this test catches such regressions. Backend regression: 733/733 pass.', 'TaxReturnComputeService.computeCombatPay line ~10228 (breadcrumb); resolveSpouseIdentification + overlayResolvedField at lines 151, 3902 (the implicit merger); test combatPayUsesSpouseSsnFromIdentificationSpouseFormViaOverlay', 'CLOSED — verified correct, no code-behavior change. The implicit overlay is now both annotated at the call site AND protected by a lock-in test. Same pattern shape as line 1h #3 (audit false positive with breadcrumb).'],
  [4, 'DEFENSIVE GAP — sumW2Box12ByCodes WITH NULL SSN SUMS ALL ENTRIES — RESOLVED 2026-05-10 (Option A scope)', 'Pre-fix: sumW2Box12ByCodes (line ~10897) skips the SSN filter when ssn is null/empty — `if (hasText(normalizedSsn))` skip-pattern. So sumW2Box12ByCodes(w2Entries, COMBAT_PAY_CODES, null) returned the SUM OF ALL code Q entries regardless of attribution. If `you.ssn` or `spouse.ssn` were null in production (incomplete onboarding, deleted profile, late-bound form save), the corresponding "total" absorbed everyone\'s code Q. Combined with electTaxpayer=true, taxpayer would receive a duplicated/inflated combat pay attribution. Post-fix (Option A — defensive at caller, scoped to line 1i): added `hasText(ssn)` guards at the two combat-pay sum sites in computeCombatPay (lines ~10244-10254). New pattern: `taxpayerTotal = hasText(taxpayerSsn) ? sumW2Box12ByCodes(...) : null` and `spouseTotal = (isMfsReturn || !hasText(spouseSsn)) ? null : sumW2Box12ByCodes(...)`. Eight-line breadcrumb comment added above the guards citing audit ID + Option A scope + Option C deferred reference. Lock-in test `combatPayWithNullTaxpayerSsnDoesNotAbsorbCodeQFromOtherW2s` — Single filer with `you` form lacking ssn + electCombatPay=true + an unrelated W-2 (employeeSSN=333-33-3333) with code Q $5,000 → asserts line 1i = BigDecimal.ZERO (NOT $5,000 absorbed). Aligns with spec §10.4 (elected with no code Q → 0, not null). Broader Option C cleanup (change sumW2Box12ByCodes helper itself to return null on null SSN, audit Saver\'s Credit at lines 19687/19730) deferred to outstanding.md ("Helper sumW2Box12ByCodes — Defensive Null-SSN Handling (Option C Broader Cleanup)", ~30-45 min scope). Backend regression: 734/734 pass.', 'TaxReturnComputeService.computeCombatPay lines ~10244-10254 (hasText guards); test combatPayWithNullTaxpayerSsnDoesNotAbsorbCodeQFromOtherW2s', 'CLOSED via Option A. Line 1i no longer absorbs unrelated code Q W-2s when taxpayer/spouse SSN is missing. Option C broader helper cleanup tracked in outstanding.md.'],
  [5, 'TEST COVERAGE GAPS — RESOLVED 2026-05-10', 'Pre-fix: 7 audit-identified sub-gaps in unit-test coverage for line 1i — (a) MFS guard, (b) MFJ all 4 election combinations, (c) multiple W-2s for same person, (d) spouse code Q not absorbed when only taxpayer elects, (e) mixed code Q + non-Q codes, (f) electCombatPay = null vs false, (g) electCombatPay = true with $0 code Q amount, (h) null taxpayer SSN with code Q. Sub-gaps (a) and (h) were closed earlier today by Issues #1 and #4 respectively (lock-in tests `mfsExcludesSpouseCombatPayElectionFromLine1i` and `combatPayWithNullTaxpayerSsnDoesNotAbsorbCodeQFromOtherW2s`). Post-fix: added 7 unit tests covering the remaining 6 sub-gaps (b split into both-elect and neither-elect): `combatPayMfjBothSpousesElect_aggregatesToLine1i` (T $2,000 + S $1,500 → $3,500); `combatPayMfjNeitherSpouseElects_line1iIsNull` (both have Q but neither elects → null); `combatPayMultipleW2sForSamePersonAreSummed` ($800 + $200 → $1,000); `combatPaySpouseCodeQNotAbsorbedWhenOnlyTaxpayerElects` (T $500, S $1,200, only T elects → $500); `combatPaySumsOnlyCodeQNotOtherBox12Codes` (Q $1,000 + D $5,000 → $1,000); `combatPayElectionNullTreatedAsNoElection` (electCombatPay=null → null); `combatPayElectsWithZeroCodeQAmount_returnsZeroNotNull` (Q $0 + elected=true → BigDecimal.ZERO). Total line-1i unit-test count: 4 → 11 (or 13 counting Issue #1, #3, #4 lock-ins). Backend regression: 741/741 pass.', 'TaxReturnComputeServiceTest — 7 new tests added after combatPayWithNullTaxpayerSsnDoesNotAbsorbCodeQFromOtherW2s', 'CLOSED — coverage sub-gaps (a)–(h) all closed. Combined with Issue #1 (MFS guard test), Issue #3 (SSN-overlay test), Issue #4 (null-SSN test), Issue #2 (EIC source-of-truth tests), line 1i has comprehensive unit-test coverage across all known scenarios.'],
  [6, 'KNOWLEDGE FILE NAMING DEVIATION — RESOLVED 2026-05-10', 'Pre-fix: `knowledge/knowledge-line-1i-combat-pay.md` used the legacy `knowledge-line-1i-` prefix while line 1c–1h had converged on `line-{N}-{topic}.md` (hyphen form, no `knowledge-` prefix). It was the only `knowledge/` file still using the legacy variant. Post-fix: file renamed to `knowledge/line-1i-combat-pay.md` via plain `mv` (`knowledge/` lives outside the `us-tax-be/` git repo). Generator header comment (line 6) updated to reference the new path; file content had no self-references. Naming now consistent across line 1c–1i. Older legacy `knowledge_line<n>.md` files (lines 8, 9, 10–33, 3ab, 4abc) remain — future sweep, out of scope. Same shape as line 1g #5 and line 1h #5.', 'knowledge/ folder; XLS/_tools/generate-1i.js (header comment line 6)', 'CLOSED. Hyphen-no-prefix convention now consistent across all line 1c–1i knowledge files.'],
  [7, 'OBSERVATION — IRA COMPENSATION NOT WIRED TO COMBAT PAY — DEFERRED PER AUDIT 2026-05-10', 'Pre-fix: per IRC §219(f)(7) and IRS Pub. 590-A Section 2, nontaxable combat pay counts as compensation for IRA contribution purposes (statutory exception to the general nontaxable-income exclusion). The rule is INDEPENDENT of the line-1i credit election — combat pay counts as IRA compensation regardless of whether the taxpayer elected the line-1i credit treatment. Verification: the IRA paths in TaxReturnComputeService cover ONLY distributions (computeIraDistributions at line 4832, handling Form 1040 lines 4a/4b). The IRA contribution DEDUCTION (Schedule 1 line 20) is read as a user-entered value at line ~7317 — there is NO backend compensation-cap validation logic anywhere. So this is not specifically a line-1i gap; it is one of several IRC §219 compensation components that would be needed once IRA-contribution-cap validation is implemented at all. Closure (per audit "Defer" recommendation): added deferred-enhancement section to outstanding.md ("Line 1i — Nontaxable Combat Pay as IRA Contribution Compensation (IRC §219(f)(7)) — Deferred 2026-05-10") with full re-implementation scope tied into the broader IRA-cap feature (~1-2 hours total; combat-pay piece ~5 min within that). Note for re-implementation: combat-pay piece must use `sumW2Box12ByCodes(w2Entries, COMBAT_PAY_CODES, personSsn)` (the underlying sum) NOT `form1040.income.nontaxableCombatPayElection` — §219(f)(7) is election-independent. No code change today; no test, no breadcrumb (no current line to attach to — this is about ABSENT logic in a not-yet-implemented compensation-cap path). Backend stays at 741/741.', 'IRA deduction read at TaxReturnComputeService.java:~7317 (user-entered value, no cap validation); outstanding.md ("Line 1i — Nontaxable Combat Pay as IRA Contribution Compensation")', 'CLOSED via deferred-enhancement entry. Per audit recommendation, no code change today. Affected users (military filers contributing to IRAs from combat pay) typically already understand the §219(f)(7) compensation expansion per Pub. 3.'],
  [8, 'OBSERVATION — TOP-OF-FORM combat_zone CHECKBOX NOT WIRED — DEFERRED PER AUDIT 2026-05-10', 'Pre-fix: Form 1040 top-of-form checkbox `topmostSubform[0].Page1[0].c1_2[0]` (semantic name `top_combat_zone`, label "If you served in a combat zone…") exists in pdfs/f1040_field_mapping_semantic.csv but has NO backend or UI wiring — grep of us-tax-be/src for top_combat_zone / combat_zone / topCombatZone / servedInCombatZone returns zero matches. The checkbox signals to the IRS that the return may qualify for deadline-extension relief per Pub. 3 §7 (180 days after leaving zone + days remaining in filing period when entered). Purely an administrative marker — does not affect tax, deductions, credits, AGI, refund, or any computed amount. Distinct from line 1i math (which affects EIC and ACTC). Closure (per audit "Defer" recommendation): added deferred-enhancement section to outstanding.md ("Form 1040 Top-of-Form combat_zone Checkbox — Filing Deadline Extension Marker — Deferred 2026-05-10") with full re-implementation scope (~30-45 min: new personal-form field, NOT auto-derived from code Q because combat-zone service is broader than nontaxable combat pay). Nuance noted: auto-derivation from code Q presence is insufficient — taxpayer can be in zone briefly without code Q, and code Q is W-2 annual reporting while this checkbox is administrative real-time eligibility. Correct implementation needs an explicit user-facing checkbox. No code change today; no test, no breadcrumb. Backend stays at 741/741. Best bundled with the deferred IRC §219(f)(7) IRA-compensation enhancement (Issue #7) as a future "military filer enhancements" track.', 'pdfs/f1040_field_mapping_semantic.csv line 1 (top_combat_zone PDF field present); zero wiring in us-tax-be/src or us-tax-ui/src (apart from EIC-election text unrelated to this checkbox); outstanding.md ("Form 1040 Top-of-Form combat_zone Checkbox")', 'CLOSED via deferred-enhancement entry. Pure clerical gap with no tax-correctness impact. Affected users (deployed military filers) have alternative deadline-extension paths (Form 4868, written request).'],
  [9, 'VERIFIED CORRECT — LINE 1z EXPLICITLY EXCLUDES LINE 1i — VERIFIED CORRECT 2026-05-10', 'Audit observation re-verified at TaxReturnComputeService.java line 4136-4140: totalWagesRaw = addNonNull(...) with exactly 8 components (line1a through line1h) — line1i is intentionally absent. Inline comment at line 4137 explicitly states "Form 1040 line 1z = sum of lines 1a-1h only (line 1i combat pay election is excluded)". Same exclusion holds for line 9 (line 9 = 1z + 2b + 3b + 4b + 5b + 6b + 7a + 8 — all excluding 1i). Hence AGI and taxable income are also unaffected. Existing lock-in test `computesLine1zSumExcludesCombatPayElection` (TaxReturnComputeServiceTest line 6291) asserts: W-2 with wages $5,000 + code Q $1,500 + electCombatPay=true → line 1z = $5,000 (wages only, no combat pay added). Spot-checked end-of-day 2026-05-10 — still passes. Audit-revisited-as-verified-and-documented closure: existing inline comment at line 4137 extended with audit ID + verification date + lock-in test name. Future reviewers can trace the exclusion intent in one read.', 'TaxReturnComputeService.java:4137 (extended breadcrumb); test computesLine1zSumExcludesCombatPayElection at TaxReturnComputeServiceTest:6291', 'CLOSED — verified correct, no fix needed. Lock-in test provides protection against accidental re-coupling of line 1i into line 1z / line 9 / AGI / taxable income.'],
  [10, 'VERIFIED CORRECT — ALL-OR-NONE PER PERSON ENFORCED — VERIFIED CORRECT 2026-05-10', 'Audit observation re-verified at computeCombatPay lines ~10264-10269: `taxpayerElected = Boolean.TRUE.equals(electTaxpayer) ? (taxpayerTotal == null ? BigDecimal.ZERO : taxpayerTotal) : null;` (and symmetric for spouseElected). Pure boolean gate — no partial-amount path. UI offers no partial-amount input (form-combat-pay-{taxpayer,spouse}.component.ts only renders a Yes/No radio for electCombatPay). Matches spec §10.2 ("All-or-none per person") + §10.4 ("elected with no code Q → 0, not null"). The BigDecimal.ZERO carve-out distinguishes "user elected but no Q found" from "user did not elect" — needed by downstream credit-worksheet consumers (Schedule 8812 line 18b disclosure shows 0 explicitly; EIC sees a deliberate $0 addition rather than treating the field as absent). Lock-in tests: `combatPayElectionWithoutCodeQIsZero` (elected, no Q W-2 at all → 0); `combatPayElectsWithZeroCodeQAmount_returnsZeroNotNull` (elected, Q present with $0 amount → 0; from Issue #5); `combatPayElectionNullTreatedAsNoElection` (electCombatPay=null → no contribution; from Issue #5); `combatPayMfjBothSpousesElect_aggregatesToLine1i` (both elect → sum; from Issue #5). Four-layer protection. Audit-revisited-as-verified-and-documented closure: 8-line breadcrumb comment added above the ternary citing audit ID + verification date + all four lock-in test names.', 'computeCombatPay lines ~10264-10269 (breadcrumb); 4 lock-in tests in TaxReturnComputeServiceTest', 'CLOSED — verified correct, no fix needed. Comprehensive multi-test lock-in protection against accidental introduction of partial-amount election or removal of the ZERO carve-out.'],
];
const ws6 = XLSX.utils.aoa_to_sheet(codeIssues);
ws6['!cols'] = [{ wch: 4 }, { wch: 28 }, { wch: 95 }, { wch: 60 }, { wch: 95 }];
XLSX.utils.book_append_sheet(wb, ws6, 'Code Validation');

// ─── Sheet 7: Output Flow ─────────────────────────────────────────────────
const output = [
  ['OUTPUT — Where Line 1i Flows in the Return'],
  [],
  ['Output Field Path', 'Output PDF Field', 'Output Form (XLS)', 'Notes'],
  ['form1040.income.nontaxableCombatPayElection', 'topmostSubform[0].Page1[0].f1_56[0] (line1i_nontaxable_combat_pay)', 'form-tax-return-1040.xlsx (line 1i cell)', '★ Primary output — printed on Form 1040 line 1i. Stored only when non-null. Whole-dollar HALF_UP rounding. Distinct from line 1z; explicitly NOT included in totalWages or AGI.'],
  ['(no separate statement attachment)', '(no PDF write-in or appended page)', '—', 'Per IRS 2023 Pub. 3 update, no "NCP" notation is required. Line 1i value alone IS the election.'],
  [],
  ['DOWNSTREAM CONSUMERS (line 1i feeds these computations)'],
  ['Schedule 8812 line 18a (earned income for ACTC)', 'topmostSubform[0].Page1[0].f1_18a[0] (or per Schedule 8812 PDF mapping)', 'form-tax-return-schedule8812.xlsx', 'line18a = totalWages + nontaxableCombatPayElection. Wired CORRECTLY at TaxReturnComputeService line 19087-19096 using the form 1040 income object as single source of truth.'],
  ['Schedule 8812 line 18b (combat pay disclosure)', 'topmostSubform[0].Page1[0].f1_18b[0] (or per Schedule 8812 PDF mapping)', 'form-tax-return-schedule8812.xlsx', 'line18b = nontaxableCombatPayElection (echoes line 1i value as a disclosure). The IRS uses line 18b to trace what portion of line 18a came from combat pay vs taxable wages.'],
  ['EIC earned-income worksheet (line 27a)', 'EIC worksheet (NOT a separate PDF line — internal calculation)', 'form-tax-return-1040.xlsx (line 27a EIC cell)', 'earnedIncomeForEic = normalEarnedIncome + electedCombatPay. EIC is then looked up using the LESSER of earnedIncomeForEic or AGI. INCONSISTENT WIRING TODAY — EIC code reads its own duplicate election flag rather than the line-1i value (Code Validation #2).'],
  [],
  ['NOT IN OUTPUT (explicit exclusions)'],
  ['Form 1040 line 1z (totalWages)', 'topmostSubform[0].Page1[0].Line1z_TotalWages', 'form-tax-return-1040.xlsx', 'EXCLUDED. line1z = sum(1a..1h) only. Verified at TaxReturnComputeService.java:4136-4138 with inline comment + lock-in test computesLine1zSumExcludesCombatPayElection.'],
  ['Form 1040 line 9 (total income)', 'topmostSubform[0].Page1[0].Line9_TotalIncome', 'form-tax-return-1040.xlsx', 'EXCLUDED. line9 = line1z + 2b + 3b + 4b + 5b + 6b + 7a + 8 — all of which exclude line 1i.'],
  ['Form 1040 line 11b (AGI)', 'topmostSubform[0].Page1[0].Line11b_AGI', 'form-tax-return-1040.xlsx', 'EXCLUDED. AGI = line9 - line10. Combat pay never enters either operand.'],
  ['Form 1040 line 15 (taxable income)', 'topmostSubform[0].Page1[0].Line15_TaxableIncome', 'form-tax-return-1040.xlsx', 'EXCLUDED. Taxable income = AGI - deductions; combat pay was never taxable to begin with.'],
  ['Schedule 1 / Schedule 2', '—', '—', 'EXCLUDED. Combat pay does not appear on any Schedule.'],
];
const ws7 = XLSX.utils.aoa_to_sheet(output);
ws7['!cols'] = [{ wch: 55 }, { wch: 70 }, { wch: 50 }, { wch: 90 }];
XLSX.utils.book_append_sheet(wb, ws7, 'Output Flow');

// Write
XLSX.writeFile(wb, OUTPUT);
console.log('Wrote: ' + OUTPUT);
