# Generate ../walkthrough.md from screens/NNN-*.json captures + shell/NNN-ocr.txt (meter/FAQ OCR) + tools/notes.jsonl.
# Usage: python gen-walkthrough.py
import json, os, re, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
notes = {}
for line in open(os.path.join(ROOT, 'tools', 'notes.jsonl'), encoding='utf8'):
    line = line.strip()
    if line:
        d = json.loads(line); notes[d['n']] = d
tabs_order = ['PERSONAL INFORMATION', 'INCOME', 'ADJUSTMENTS', 'DEDUCTIONS', 'CREDITS', 'TAXES', 'MISC', 'FINISH',
              'GETTING STARTED', 'IMPORT', 'EXTENSION']

def meter_and_faq(n):
    p = os.path.join(ROOT, 'shell', '%03d-ocr.txt' % n)
    if not os.path.exists(p):
        return None, [], None
    lines = [l.strip() for l in open(p, encoding='utf8', errors='replace') if l.strip()]
    fed = None; change = None; faqs = []; inleft = False; seen_faq = False
    for i, l in enumerate(lines):
        if l.startswith('--- LEFT'): inleft = True; continue
        if l.startswith('--- TABS'): inleft = False; continue
        if inleft:
            if l == 'FEDERAL REFUND' or l == 'FEDERAL TAX DUE':
                for k in lines[i + 1:i + 4]:
                    if k.startswith('$'): fed = (('owe ' if 'DUE' in l else '') + k.replace(' ', '')); break
            if re.match(r'^[Av^▲]?\s*(Increase|Decrease) of', l): change = re.sub(r'^[Av^]\s*', '', l)
            if l == 'FAQs': seen_faq = True; continue
            if seen_faq and l not in ('View Details',):
                faqs.append(l)
    # re-join FAQ fragments into questions
    qs, cur = [], ''
    for f in faqs:
        cur = (cur + ' ' + f).strip()
        if cur.endswith('?') or cur.endswith('...'):
            qs.append(cur); cur = ''
    if cur: qs.append(cur + ' (…)')
    return fed, qs, change

out = ['# H&R Block Software 2025 (Premium) — chronological walkthrough', '',
       'Generated by `tools/gen-walkthrough.py` from the per-screen captures in `screens/` (PNG + JSON: full text, every input with',
       'field id/label/value, buttons, help links) plus native-shell captures in `shell/` (whole window PNG + OCR of the',
       'refund meter and the contextual FAQ panel). Household: fictional MFJ couple Jordan & Casey Sample (IL) + son Riley.',
       'Screen numbers are capture order; a number may show the same screen before/after an action (noted).', '',
       'Type legend: Intro/Interstitial · Question (Y/N) · Question (choice) · Entry · Checklist · Gateway/Hub · Summary/List ·',
       'Outcome/Eligibility result · Help pop-up (h*) · Variant/What-if (v*) · Review/Error-check · Upsell.', '']
files = sorted(glob.glob(os.path.join(ROOT, 'screens', '[0-9][0-9][0-9]-*.json')))
for f in files:
    d = json.load(open(f, encoding='utf8'))
    n = d.get('n'); nt = notes.get(n, {})
    if not d.get('topics'):
        d['topics'] = list(dict.fromkeys(re.findall(r'TOPICHELP=([^,]+)', ' '.join(b.get('href') or '' for b in d.get('buttons', [])))))
    title = d.get('title') or (d.get('text', '')[:80])
    png = os.path.basename(f)[:-5] + '.png'
    out.append('### %03d — %s' % (n, title))
    out.append('')
    out.append('- **Image:** `screens/%s`%s' % (png, ('  ·  shell: `shell/%03d.png`' % n) if os.path.exists(os.path.join(ROOT, 'shell', '%03d.png' % n)) else ''))
    out.append('- **Type:** %s%s' % (nt.get('type', d.get('type', '(unclassified)')), ('  ·  **Topic:** `%s`' % ','.join(d['topics'])) if d.get('topics') else ''))
    if d.get('type') == 'Help pop-up':
        out.append('- **Help text:** %s' % d.get('text', '')[:900])
    else:
        fed, faqs, change = meter_and_faq(n)
        if fed: out.append('- **Meter:** Federal refund %s%s' % (fed, ('  (latest change: %s)' % change) if change else ''))
        txt = d.get('text', '')
        out.append('- **Content:** %s' % (txt[:600] + ('…' if len(txt) > 600 else '')))
        ins = d.get('inputs', [])
        if ins:
            parts = []
            for i in ins[:40]:
                lab = re.sub(r'\s+', ' ', i.get('label') or '')[:70]
                v = i.get('value') or ''
                ck = '' if i.get('checked') is None else (' [x]' if i['checked'] else ' [ ]')
                parts.append('`%s` %s%s%s' % (i['name'], i.get('type') or i.get('tag'), ck, (' "%s"' % lab) if lab else ''))
            out.append('- **Controls (%d):** %s%s' % (len(ins), '; '.join(parts), ' …' if len(ins) > 40 else ''))
        btns = [b for b in d.get('buttons', []) if b.get('img') or b.get('text')]
        nav = [(b.get('img') or b.get('text')) for b in btns if 'navbtn' in (b.get('cls') or '') or 'contentbtn' in (b.get('cls') or '')]
        if nav: out.append('- **Buttons:** %s' % ', '.join(dict.fromkeys(nav)))
        helps = [b for b in btns if (b.get('href') or '').lower().startswith('tc:topichelp')]
        if helps:
            out.append('- **Help affordances:** %s' % '; '.join('%s → `%s`' % (b.get('text') or b.get('img'), b['href'].split('=', 1)[1]) for b in helps[:12]))
        dfaq = [l['text'] + ' (`' + l['href'].split('=',1)[-1] + '`)' for l in d.get('topicLinks', []) if l.get('faq') and l.get('text')]
        if dfaq: out.append('- **Left-panel FAQs:** %s' % ' | '.join(dict.fromkeys(dfaq)))
        elif faqs: out.append('- **Left-panel FAQs (OCR):** %s' % ' | '.join(faqs[:8]))
        if d.get('dialogs'): out.append('- **JS dialogs:** %s' % '; '.join(d['dialogs']))
        if d.get('actionsBefore'):
            out.append('- **Actions taken to reach/fill:** `%s`' % json.dumps(d['actionsBefore'])[:300])
    if nt.get('note'): out.append('- **Notes:** %s' % nt['note'])
    out.append('')
open(os.path.join(ROOT, 'walkthrough.md'), 'w', encoding='utf8').write('\n'.join(out))
print('screens:', len(files), 'notes:', len(notes))
